export const tabBarStyle = {
  position: "absolute",
  alignItems: "center",
  zIndex:2,
  backgroundColor: "white",
  shadowOpacity: 0.15,
  shadowRadius: 4,
  shadowColor: "black",
  shadowOffset: { width: 2, height: 2 },
  height: 60,
  borderRadius: 16,
  bottom: 16,
  left: 16,
  right: 16,
};
